Document: fba
Title: Debian fba Manual
Author: <insert document author here>
Abstract: This manual describes what fba is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fba/fba.sgml.gz

Format: postscript
Files: /usr/share/doc/fba/fba.ps.gz

Format: text
Files: /usr/share/doc/fba/fba.text.gz

Format: HTML
Index: /usr/share/doc/fba/html/index.html
Files: /usr/share/doc/fba/html/*.html

  
